### ISSUE TITLE
[1.12.2]Floating friends model

### ISSUE THREAD

**Issue by YueLengM** [pentantan/JapariCraftMod#14]
![snipaste_180506_192420](https://user-images.githubusercontent.com/11801894/39672767-32de20bc-5163-11e8-9661-3bbd9b91b622.png)
![snipaste_180506_192523](https://user-images.githubusercontent.com/11801894/39672768-33175e18-5163-11e8-9625-e99e2ac66ffc.png)

**Comment by pentantan** [comment]
![dcwsutou0aaour- jpg-large](https://user-images.githubusercontent.com/23486561/39839702-08af43f4-5418-11e8-8f23-65e6cc3e684c.jpeg)
I Fix it :)
