### ISSUE TITLE
Any method to avoid "friend fire"

### ISSUE THREAD

**Issue by ZechCal** [pentantan/JapariCraftMod#20]
What a cute mod!(￣▽￣)"! I'm wonder if there is a method to avoid friend fire, this often happened when fighting with mobs, and another suggestion is that if you hurt your friend with intention, then your friend might be go away. 

Hope this helps :>

**Comment by pentantan** [comment]
https://gyazo.com/93aee47f12893d6fb05ff08ba5f50c15
friend fire disable! 
enjoy friends life! :)
