### ISSUE TITLE
translation file (zh_TW.lang)

### ISSUE THREAD

**Issue by ckhomo** [pentantan/JapariCraftMod#21]
初めまして、開発者さん。

中国語(繁体字)の翻訳ファイル作ったのでここにアップロードしました。
[zh_TW.lang.txt](https://github.com/pentantan/JapariCraftMod/files/2202245/zh_TW.lang.txt)

modに対するいつもの開発とメンテナンス、ここで厚く感謝申し上げます。
では。

**Comment by pentantan** [comment]
ありです～
