### ISSUE TITLE
Sometimes SHIFT+RIGHT didn't works

### ISSUE THREAD

**Issue by ZechCal** [pentantan/JapariCraftMod#23]
This issue is spotted in newest 4.4.5

**Comment by pentantan** [comment]
![7f0b5b92a71ec9990da6d81c12fd1cf1](https://user-images.githubusercontent.com/23486561/42989656-7a940ada-8c3b-11e8-80d0-a77f958c6479.gif)
I fix it

**Comment by ZechCal** [comment]
Great! Got it!
