### ISSUE TITLE
Using a name tag to name a friend you tamed causes server/client desync

### ISSUE THREAD

**Issue by bbbbbbbbba** [pentantan/JapariCraftMod#28]
If you tame a friend, then try to name it with a name tag, it seems to succeed, but after saving and reloading the game, the name doesn't stick, and the name tag is returned to your inventory (it also reappears if you try to use its inventory slot).

The bug is caused by a server/client desync: the client thinks the naming succeeds but the server never sees the naming event. It is caused by the following code snippet in `EntityFriend.java`:

    if (this.isOwner(player) && !this.world.isRemote) {

        this.aiSit.setSitting(!this.isSitting());

        return true;

    }

The `return true;` stops the item's own right click functionality --- but only on the server side.

As an aside, this `return true;` really should appear in the previous "if" block:

    if (player.isSneaking() && !this.isSitting()) {

        player.openGui(JapariCraftMod.instance, JapariCraftMod.ID_JAPARI_INVENTORY, this.getEntityWorld(), this.getEntityId(), 0, 0);

    }

The absence of a `return true;` here causes the friend to sit down when shift+right clicked (I don't know if that is intended), but also results in some more strange behavior. For example, if your hunger bar is not full and you shift+right click a friend with some food in hand, then you will consume the food soon after opening the GUI --- even if you don't hold the right mouse button.

**Comment by bbbbbbbbba** [comment]
Also, I don't know why Alpaca and Araisan need to override `processInteract`; their version of `processInteract` seems barely different from the `EntityFriend` version, except in the last line `super.processInteract` now refers to `EntityFriend.processInteract`, which caused trouble for me when I tried to fix this bug.

**Comment by pentantan** [comment]
I Fix it on 5.0.2 :)
