### ISSUE TITLE
crash while exploring on server(1.12.2)

### ISSUE THREAD

**Issue by SDUBZ** [pentantan/JapariCraftMod#3]
Forge: 1.12.2-2575
japaricraft: japaricraftmod-1.12-3.4.0

crash report:
[crash-2017-12-29_06.13.44-server.txt](https://github.com/pentantan/JapariCraftMod/files/1593163/crash-2017-12-29_06.13.44-server.txt)

**Comment by SDUBZ** [comment]
also got this crash when testing with new forge and mod
Forge:1.12.2-2582
japaricraft: japaricraftmod-1.12-3.4.2

crash report:
[crash-2017-12-30_00.55.32-server.txt](https://github.com/pentantan/JapariCraftMod/files/1593214/crash-2017-12-30_00.55.32-server.txt)

**Comment by pentantan** [comment]
Are you using a version that may contain bugs?
We usually recommend using stable version
