### ISSUE TITLE
Couldn't render entity console spam

### ISSUE THREAD

**Issue by AlucardBFahrenheit** [pentantan/JapariCraftMod#32]
When looking at a japaricraft entity or if I am near one I get console spam saying the following:

![image](https://user-images.githubusercontent.com/38115411/53700533-d5832600-3df3-11e9-86c7-2059caa71175.png)

And frequently also this:
"baguchan.japaricraftmod.client.model.ModelSquirre cannot be cast to net.minecraft.client.model.ModelBiped" which is also spammed into the console.

When that happens usually every mob in my field of vision is "sent flying" around the screen and upside down mobs are walking around, water is also not being rendered in that state and the sky goes full static.

I tried to capture an image of that happening but it was hard, the only thing I could capture was this:
![2019-03-03_20 33 50](https://user-images.githubusercontent.com/38115411/53700627-9b665400-3df4-11e9-80d5-7f3d8f459186.png)

Additionally I can say that I **don't** have optifine or any other mod that changes the game rendering installed, no shader is used and the config of the mod was unmodified.

If any more information is needed I'd be happy to provide it.

**Comment by pentantan** [comment]
Is JapariCraftMod newer vesion?

**Comment by AlucardBFahrenheit** [comment]
It's the latest version that is on curseforge.

**Comment by pentantan** [comment]
![default](https://user-images.githubusercontent.com/23486561/54047592-d44e6080-421a-11e9-993e-d21d8026c1bc.PNG)
Perhaps, I think that it is causing a render error due to the gun held by friends
Please tell me if you get an error even if you just insert **japaricraftmod only**
