### ISSUE TITLE
[1.12.2] PriceRange error...

### ISSUE THREAD

**Issue by PhoenixRiver** [pentantan/JapariCraftMod#6]
Version: japaricraftmod-1.12-3.7.1

I think I have finally managed to track this error down to the JapariCraftMod; apparently it is a problem with the items added for sale with villagers, I'm guessing the maximum and minimum are switched so you need to reverse them (here is the error message in the Minecraft logs):

```
[23:06:00] [main/WARN]: PriceRange(-10, -18) invalid, -18 smaller than -10
[23:06:00] [main/WARN]: PriceRange(-10, -18) invalid, -18 smaller than -10
[23:06:00] [main/WARN]: PriceRange(-10, -18) invalid, -18 smaller than -10
```

Your code should have `PriceRange(-18,-10)` instead :)

Hope this helps :)

**Comment by PhoenixRiver** [comment]
I just found the error, it's in the file:
JapariCraftMod/src/main/java/com/japaricraft/japaricraftmod/handler/ModVillagers.java

On lines 70, 71 and 73:

```
        career_zookeeper.addTrade(2,
                **new EntityVillager.ListItemForEmeralds(JapariItems.japariman, new EntityVillager.PriceInfo(-10, -18)),**
                **new EntityVillager.ListItemForEmeralds(JapariItems.japarimanapple, new EntityVillager.PriceInfo(-10, -18)),**
                new EntityVillager.ListItemForEmeralds(JapariItems.kabanhat, new EntityVillager.PriceInfo(1, 2)),
                **new EntityVillager.ListItemForEmeralds(JapariItems.japarimancocoa, new EntityVillager.PriceInfo(-10, -18))**
);
```

**Comment by pentantan** [comment]
I fixed
thank you!

**Comment by PhoenixRiver** [comment]
Thank you :)
