### ISSUE TITLE
[1.12.2] .config file comment mistake...

### ISSUE THREAD

**Issue by PhoenixRiver** [pentantan/JapariCraftMod#7]
Version: japaricraftmod-1.12-3.7.1

Very small error indeed! The first setting in the config file for JapariCraftMod should say:
`
    # Changes spawn rate of BlackCerulean. Increase value to spawn more BlackCerulean.
`
(It says "PoisonCerulean" the second time in that sentence).

Hope this helps :)

**Comment by pentantan** [comment]
I fix it :)
